
platform :ios, ‘8.0’
use_frameworks!

target 'LLTravel' do
  pod 'AFNetworking', '~> 3.1.0’
	pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.6'
pod 'SDCycleScrollView', '~> 1.64'
end
  
